/**
 * @dcyfr/ai-code-gen - AI Provider Interface
 *
 * Abstraction layer for LLM providers with a mock provider for testing.
 */

import type { AIProviderConfig, AICodeRequest, AICodeResponse } from '../types/index.js';
import { generateCodePrompt } from './prompts.js';

/** AI provider interface */
export interface AIProvider {
  /** Provider name */
  readonly name: string;
  /** Generate code from a request */
  generate(request: AICodeRequest): Promise<AICodeResponse>;
  /** Generate a raw completion from a prompt */
  complete(prompt: string): Promise<string>;
}

/**
 * Mock AI provider for testing and offline development.
 * Generates deterministic placeholder code based on the request.
 */
export class MockAIProvider implements AIProvider {
  readonly name = 'mock';

  async generate(request: AICodeRequest): Promise<AICodeResponse> {
    const code = this.generateMockCode(request);

    return {
      code,
      explanation: `Mock-generated ${request.language} code for: ${request.prompt}`,
      language: request.language,
      confidence: 0.85,
      usage: {
        promptTokens: request.prompt.length,
        completionTokens: code.length,
        totalTokens: request.prompt.length + code.length,
      },
    };
  }

  async complete(prompt: string): Promise<string> {
    return `// Mock completion for prompt (${prompt.length} chars)\n// TODO: Replace with real AI provider\n`;
  }

  private generateMockCode(request: AICodeRequest): string {
    const lang = request.language.toLowerCase();

    if (lang === 'typescript' || lang === 'ts') {
      return this.generateTypeScriptMock(request);
    }

    return `// ${request.language} code for: ${request.prompt}\n// Generated by mock provider\n`;
  }

  private generateTypeScriptMock(request: AICodeRequest): string {
    const lines = [
      `/**`,
      ` * ${request.prompt}`,
      ` * `,
      ` * @generated by @dcyfr/ai-code-gen (mock)`,
      ` */`,
      ``,
    ];

    if (request.framework) {
      lines.push(`// Framework: ${request.framework}`);
    }

    if (request.constraints && request.constraints.length > 0) {
      lines.push(`// Constraints: ${request.constraints.join(', ')}`);
    }

    lines.push(
      ``,
      `export function generatedFunction(): void {`,
      `  // TODO: Implement ${request.prompt}`,
      `  console.log('Generated code placeholder');`,
      `}`,
      ``,
    );

    return lines.join('\n');
  }
}

/**
 * Create an AI provider from configuration.
 * Currently supports 'mock' provider; real providers can be added later.
 */
export function createAIProvider(config: AIProviderConfig): AIProvider {
  switch (config.provider) {
    case 'mock':
      return new MockAIProvider();
    case 'openai':
    case 'anthropic':
    case 'local':
      // Return mock with a warning for unsupported providers
      console.warn(
        `AI provider '${config.provider}' is not yet implemented. Using mock provider.`,
      );
      return new MockAIProvider();
    default:
      throw new Error(`Unknown AI provider: ${config.provider}`);
  }
}

// Re-export for convenience
export { generateCodePrompt };
